---

- name: remove example apache files
  file:
    name: "{{ apache_configuration_dir }}/{{ item }}"
    state: absent
  loop:
    - userdir.conf
    - welcome.conf
  notify: restart apache

- name: setup project
  template:
    src: index.html.j2
    dest: "{{ apache_default_docroot }}/index.html"
  notify: restart apache
